### ISSUE TITLE
Se puede descargar cualquier indicador de inegi o solo los de BIE?

### ISSUE THREAD

**Issue by JavierParada** [andreslomeliv/DatosMex#3]
Hola!

Se puede descargar cualquier indicador de inegi o solo los de BIE?

Por ejemplo, para 899250:

df = inegi.obtener_df(indicadores = ["899251"], 
                      nombres = ['Indicador Coincidente'], 
                      inicio = '2018', 
                      fin = '2023')

display(df.head())
display(df.tail())

Me da el siguiente error:

AssertionError: No se encontró información con las parámetros especificados.

Gracias!

**Comment by andreslomeliv** [comment]
Para todos los del catálogo de indicadores, ya sea BIE o BISE, checa si el
indicador está correcto o alguna otra parte de la consulta. Por ejemplo, en
la que mandas tienes al revés el año de inicio y el final.

**Comment by JavierParada** [comment]
Gracias por su pronta respuesta. 

Intento descargar series del INPC como las que se encuentran en: 

[https://inegi.org.mx/programas/inpc/2018a/#tabulados](https://inegi.org.mx/programas/inpc/2018a/#tabulados)

Puede ser que sean muy específicos para incluirse en BIE o BISE. Por ejemplo indice de precio de nopal de Aguascalientes quincenal. 

Solo quería saber si hay alguna forma de usar su paquetería de Python. Por ejemplo, en R se puede descargar así:

df <- inegi_series("899250", token, lastonly=FALSE, metadata=TRUE )
df

**Comment by andreslomeliv** [comment]
Revisé la consulta y por alguna error para que te regrese debes indicar el
banco:

df = inegi.obtener_df(indicadores = ["899251"],
    ...: nombres = ['Indicador Coincidente'],
    ...: inicio = '2010',
    ...: fin = '2018',
    ...: banco = "BIE")

Esto es un bug así que gracias por notarlo. También quería decirte que ese
indicador no es el Indicador Coincidente, entonces no estoy seguro de que
sea el que estés buscando. ¿De dónde obtuviste esa clave?

**Comment by andreslomeliv** [comment]
Se incluyen los mismos que en R, en este caso se tiene que especificar el
parámetro banco de la siguiente manera:
df = inegi.obtener_df(indicadores = ["899251"],
    ...: nombres = ['Indicador Coincidente'],
    ...: inicio = '2010',
    ...: fin = '2018',
    ...: banco = "BIE")

No estoy seguro por qué ese indicador en particular no funciona sin
especificar el banco, eso es un bug gracias por notarlo.

**Comment by JavierParada** [comment]
Gracias, una vez que agregue banco="BIE" sí funcionó

df = inegi.obtener_df(indicadores = ["899250","899251"], 
                      nombres = ['Indicador Coincidente'], inicio = '2018', 
                      fin = '2024', banco = "BIE")
df
